print('Please enter number of lives: ')
lives=int(input())
print()
print('Please enter energy level: ')
energy=int(input())
print()
print('Please enter shield level: ')
shield=int(input())
print()
print('Health has been set.')
print()
print(f"Lives:  {lives * '♥'} ")
print()
print(f"Energy: {energy * ' $'}")
print()
print(f"Sheild : {shield * '%'}")
print()
print('END')